### PR TITLE
Update ForceDotCom fork of CocoaLumberjack to the latest 2.3.0 release tag

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bhariharan** [comment]
@MikeNachbaur There are merge conflicts. You'll need to apply our changes here (rebase/merge off of `sdk`). I think most of the work is build targets and project file changes.

**Comment by ghost** [comment]
Good times, that's what I get for blindly issuing a PR.  I'll update this PR tomorrow morning.

**Comment by bhariharan** [comment]
@MikeNachbaur Let me know when this is updated, so we can get this merged in.

**Comment by bhariharan** [comment]
👍

**Pull request merged**
